function [imati]=imat_create_setup(handles)
path=get(handles.Opened_data,'String');
single=get(handles.single,'Value');
index=get(handles.Output,'String');
channel=str2num(get(handles.Channel,'String'));
resize=str2num(get(handles.Resize,'String'));
imtype=get(handles.imtype,'String');
prepro=get(handles.preprocessonoff,'Value');
preprofile=get(handles.preprofile,'String');
imatuserpre1=textread([ imat_instpath imat_userpath preprofile '.m'],'%s','delimiter','\n','whitespace','');
preprofilecontent=imatuserpre1;
unfold=get(handles.Unfold,'Value');
unfold_temp=get(handles.Unfold,'String');
method=get(handles.method,'Value');
method_temp=get(handles.method,'String');
postpro=get(handles.postprocessonoff,'Value');
postprofile=get(handles.postprofile,'String');
imatuserpost1=textread([ imat_instpath imat_userpath postprofile '.m'],'%s','delimiter','\n','whitespace','');
postprofilecontent=imatuserpost1;
gbu=get(handles.gbu,'Value');
systematic=get(handles.Systematic,'Value');
stratified=get(handles.Stratified,'Value');
keepgrid=get(handles.Keepgrid,'Value');
points=str2num(get(handles.Iter,'String'));
smax=str2num(get(handles.Smax,'String'));
points=str2num(get(handles.Iter,'String'));
gridx=str2num(get(handles.GridX,'String'));
gridy=str2num(get(handles.GridY,'String'));
amtplus=get(handles.AMTplus,'Value');
amton=get(handles.AMTon,'Value');
rmbg=get(handles.Remove_bg,'Value');
lowercutoff=str2num(get(handles.Lowercutoff,'String'));
uppercutoff=str2num(get(handles.Uppercutoff,'String'));
loweronhill=str2num(get(handles.Loweronhill,'String'));
upperonhill=str2num(get(handles.Upperonhill,'String'));
bgcutoff=str2num(get(handles.Bg_cutoff,'String'));


imati.source.path=path;
imati.source.single=single;
imati.source.channel=channel;
imati.source.resize=resize;
imati.output.index=index;
imati.source.imtype=imtype;
imati.analysis.method=method;
imati.analysis.methodtxt=method_temp(method,:);
imati.analysis.prepro=prepro;
imati.analysis.preprofile=preprofile;
imati.analysis.preprofilecontent=preprofilecontent;
imati.analysis.postpro=postpro;
imati.analysis.postprofile=postprofile;
imati.analysis.postprofilecontent=postprofilecontent;
imati.analysis.unfold=unfold;
imati.analysis.unfoldtxt=unfold_temp(unfold,:);
imati.analysis.smax=smax;
imati.analysis.points=points;
imati.grid.type.gbu=gbu;
imati.grid.type.systematic=systematic;
imati.grid.type.stratified=stratified;
imati.grid.type.keepgrid=keepgrid;
imati.grid.gridx=gridx;
imati.grid.gridy=gridy;
imati.cutting.type.plus=amtplus;
imati.cutting.type.onhill=amton;
imati.cutting.uppercutoff=uppercutoff;
imati.cutting.lowercutoff=lowercutoff;
imati.cutting.upperonhill=upperonhill;
imati.cutting.loweronhill=loweronhill;
imati.cutting.removebg=rmbg;
imati.cutting.bgcutoff=bgcutoff;
%%%%%%%%%%%%%%%%%%%%
imati.sys.softdelay=0.5;
imati.sys.mustdelay=0.1;
imati.sys.queue=0;



