function [setupnames]=gia_queue_setups
location='C:\MATLAB6p5\work\imat-16-03-05\imat\userfiles\';
setupnames=[cellstr([ location 'poly20ch01_imatsetup.mat']);...
            cellstr([ location 'poly20ch02_imatsetup.mat']);...
            cellstr([ location 'poly63ch01_imatsetup.mat']);...            
            cellstr([ location 'poly63ch02_imatsetup.mat']);...
];


